Mopas/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Mopas.Entities;
using Mopas.Models;

namespace Mopas.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly MopasDbContext _context;

        public CategoryController(MopasDbContext context)
        {
            _context = context;
        }

        public IActionResult CreateCategory()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateCategory(CategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                var category = new Category()
                {
                    CategoryName = model.CategoryName,
                };

                _context.Categories.Add(category);
                _context.SaveChanges();
            }


            return View();
        }



        public IActionResult Index()
        {
            var categories = _context.Categories;
            return View(categories);
        }

        [HttpGet]
        public IActionResult DeleteCategory([FromRoute]int id)
        {
            var category = _context.Categories.SingleOrDefault(x => x.Id == id);

            _context.Remove(category);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }


        public IActionResult UpdateCategory([FromRoute]int id)
        {
            var category = _context.Categories.SingleOrDefault(x=>x.Id == id);
            return View(category);
        }

        [HttpPost]
         public IActionResult UpdateCategory(Category model)
        { 
             
                var category = _context.Categories.SingleOrDefault(x=>x.Id == model.Id);

                category.CategoryName = model.CategoryName;
                category.Id = model.Id;

                _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }





    }
}

Mopas/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Mopas.Entities;
using Mopas.Models;

namespace Mopas.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly MopasDbContext _context;

        public ProductController(MopasDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var products = _context.Products;
             
            return View(products);
        }

        public IActionResult CreateProduct()
        {
            ViewBag.Categories = new SelectList(_context.Categories, "Id", "CategoryName");

            return View();
        }

        [HttpPost]
        public IActionResult CreateProduct(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var product= new Product()
                { 
                  ProductName = model.ProductName,
                  Description = model.Description,
                  Price = model.Price,
                  Stock = model.Stock,
                  CategoryId = model.CategoryId,
                  Category = _context.Categories.SingleOrDefault(c=>c.Id == model.CategoryId)
                };

                _context.Products.Add(product);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public IActionResult DeleteProduct([FromRoute] int id)
        {
            var product = _context.Products.SingleOrDefault(x => x.Id == id);

            _context.Remove(product);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }


        public IActionResult UpdateProduct([FromRoute] int id)
        {
            ViewBag.Categories = new SelectList(_context.Categories, "Id", "CategoryName");

            var product = _context.Products.SingleOrDefault(x => x.Id == id);
            return View(product);
        }

        [HttpPost]
        public IActionResult UpdateProduct(Product model)
        {

            var product = _context.Products.SingleOrDefault(x => x.Id == model.Id);

            product.Id= model.Id;
            product.ProductName=model.ProductName;
            product.Description=model.Description;
            product.Price=model.Price;  
            product.Stock=model.Stock;
            product.CategoryId=model.CategoryId;
             

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Mopas/Controllers/SaleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mopas.Entities;
using Mopas.Models;

namespace Mopas.Controllers
{
    [Authorize]
    public class SaleController : Controller
    {
        private readonly MopasDbContext _context;

        public SaleController(MopasDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var salesReports = _context.SalesReports;

            List<SalesReportViewModel> salesReportsViewModel = new List<SalesReportViewModel>();

            foreach (var item in salesReports)
            {
                salesReportsViewModel.Add(new SalesReportViewModel
                {
                    Id = item.Id,
                    SalesName = item.SalesName,
                    Products = item.Products,
                    SalesDate = item.SalesDate,
                    SalesQuantity = item.SalesQuantity,
                });
            }

            return View(salesReportsViewModel);
        }

        public IActionResult Get([FromRoute(Name = "id")] int id)
        {
            var salesReport = _context.SalesReports
                .Include(sr => sr.Products)
                .FirstOrDefault(sr => sr.Id == id);

            if (salesReport == null)
            {
                return NotFound();
            }

            var viewModel = new SalesReportDetailViewModel
            {
                SalesReport = salesReport,
                Products = salesReport.Products.ToList()
            };

            return View(viewModel);
        }


        public IActionResult CreateSale()
        {
            ViewBag.Products = new SelectList(_context.Products, "Id", "ProductName");

            return View();
        }

        [HttpPost]
        public IActionResult CreateSale(SalesReportViewModel viewModel)
        {
            var salesReport = new SalesReport
            {
                SalesName = viewModel.SalesName,
                SalesDate = viewModel.SalesDate,
            };


            decimal totalSalesPrice = 0;
            foreach (var productId in viewModel.SelectedProductIds)
            {
                var product = _context.Products.SingleOrDefault(p => p.Id == productId);
                if (product != null)
                {
                    salesReport.Products.Add(product);
                    totalSalesPrice += product.Price;
                }
            }
            salesReport.SalesQuantity = totalSalesPrice;
            _context.SalesReports.Add(salesReport);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        public IActionResult DeleteSaleReport([FromRoute] int id)
        {
            var salesReport = _context.SalesReports.SingleOrDefault(sr => sr.Id == id);


            _context.SalesReports.Remove(salesReport);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));

        }



        public IActionResult UpdateSalesReport([FromRoute] int id)
        {
            ViewBag.Products = new SelectList(_context.Products, "Id", "ProductName");

            var saleReport = _context.SalesReports.Include(s => s.Products).SingleOrDefault(x => x.Id == id);

            SalesReportViewModel salesReportsViewModel = new SalesReportViewModel
            {
                Id = saleReport.Id,
                SalesName = saleReport.SalesName,
                Products = saleReport.Products,
                SalesDate = saleReport.SalesDate,
                SalesQuantity = saleReport.SalesQuantity
            }; 
            return View(salesReportsViewModel);
        }


        [HttpPost]
        public async Task<IActionResult> UpdateSalesReport(SalesReportViewModel viewModel)
        {

            decimal newTotalPrice = 0;
            var salesReport = _context.SalesReports.Include(s => s.Products).SingleOrDefault(x => x.Id == viewModel.Id);
            salesReport.SalesName = viewModel.SalesName;
            salesReport.SalesDate = viewModel.SalesDate;

            salesReport.Products.Clear();

            foreach (var productId in viewModel.SelectedProductIds)
            {
                var product = await _context.Products.FindAsync(productId);
                if (product != null)
                {
                    salesReport.Products.Add(product);
                    newTotalPrice += product.Price;
                }
            }

            salesReport.SalesQuantity = newTotalPrice;


            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }


    }
}

Mopas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Market</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mopas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Market</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Kategoriler</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Ürünler</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Sale" asp-action="Index">Satış Takip</a>
                            </li>
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Çıkış Yap</a>
                            </li>

                        }
                        else
                        {

                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Register">Kayıt Ol</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Giriş Yap</a>
                            </li>

                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Mopas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>